version: '3.4'

services:
    gateway:
        container_name: gateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "7000:80"
